---
- name: Install Docker on EC2
  hosts: servers
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Dependency installation
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Docker oficial key add
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present


    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Run Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Set AWS ECR Image Variables
      set_fact:
        AWS_ACCOUNT_ID: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
        AWS_REGION: "{{ aws_region }}"
        IMAGES: ["server", "client", "nginx"]
        REPOS: ["bdg-repoarmentest-1", "bdg-repoarmentest-2", "bdg-repoarmentest-3"]


    - name: Copy docker-compose.yml to EC2
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Start Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu
      environment:
        ECR_SERVER_IMAGE: "{{ AWS_ACCOUNT_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/{{ REPOS[0] }}:latest"
        ECR_CLIENT_IMAGE: "{{ AWS_ACCOUNT_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/{{ REPOS[1] }}:latest"
        ECR_NGINX_IMAGE: "{{ AWS_ACCOUNT_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/{{ REPOS[2] }}:latest"
